const ART = [
  {"title": "Owl",
   "filename": "owl.txt",
   "credit_text": "Donovan Bake",
   "credit_url": "https://www.asciiart.eu/animals/birds-land"},
  {"title": "Earth",
   "filename": "earth.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
  {"title": "Car",
   "filename": "car_art.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
  {"title": "Deer",
   "filename" : "deer.txt",
   "credit_text" : "",
   "credit_url": "https://www.asciiart.eu/animals/deer"},
  {"title": "Dragon",
   "filename" : "dragon.txt",
   "credit_text" : "",
   "credit_url": "https://www.asciiart.eu/mythology/dragons"},
];
